config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

  resources :users, only: [:edit, :update]
  resources :appointments do
  	member do
  		get :accept_appointment, as: :accept
  	end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord

	validates :doctor_id, :patient_id, :appointment_time, :presence => true

	def doctor
		User.find(self.doctor_id)
	end

	def patient
		User.find(self.patient_id)
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, :presence => true

  enum role: [:doctor, :patient]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :doctor
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
	before_action :configure_permitted_parameters, if: :devise_controller?

	protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :role])
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController

	def new
		@appointment = Appointment.new
		@doctors = User.where(role: "doctor")
	end

	def create
		# return render body: params.inspect
		@appointment = Appointment.new(appointment_params)
		if @appointment.save
			flash[:notice] = "You have successfully set appointment with #{@appointment.doctor.name}"
			redirect_to root_path
		else
			redirect_to new_appointment_path
		end
	end

	def edit
		@appointment = Appointment.find(params[:id])
		@doctors = User.where(role: "doctor")
	end

	def update
		@appointment = Appointment.find(params[:id])
		if @appointment.update_attributes(appointment_params)
			flash[:notice] = "You have successfully update appointment with #{@appointment.doctor.name}"
			redirect_to root_path
		else
			flash[:error] = "Something went wrong. please try again."
			redirect_to edit_appointment_path(@appointment)
		end
	end

	def destroy
		@appointment = Appointment.find(params[:id])
		if @appointment.destroy
			flash[:notice] = "You have successfully delete appointment."
			redirect_to root_path
		else
			flash[:error] = "Something went wrong. please try again."
			redirect_to root_path
		end
	end

	def accept_appointment
		@appointment = Appointment.find(params[:id])
		if @appointment.update_attributes(is_accepted: true)
			flash[:notice] = "You have successfully accept appointment with #{@appointment.patient.name}."
			redirect_to root_path
		else
			flash[:error] = "Something went wrong. please try again."
			redirect_to root_path
		end
	end

	private

	def appointment_params
		params.require(:appointment).permit(:patient_id, :doctor_id, :note, :appointment_time)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@user = current_user
		if @user.role == "doctor"
			@doctor_appointments = Appointment.where(doctor_id: @user.id, is_accepted: false)
			@accepted_appointments = Appointment.where(doctor_id: @user.id, is_accepted: true)
		elsif @user.role == "patient"
			@doctors = User.where(role: "doctor")
			@booked_appointments = Appointment.where(patient_id: @user.id)
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update_attributes(user_params)
			flash[:notice] = "you have successfully update your profile."
			redirect_to root_path
		else
			redirect_to edit_user_path(@user)
		end
	end

	private

	def user_params
		params.require(:user).permit(:name, :email)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/appointments/edit.html.erb
<%= form_for @appointment, html: { multipart: true, autocomplete: "off" } do |f| %>
	<%= f.hidden_field :patient_id, value: @appointment.patient_id %>

  <div class="form-group">
    <%= f.label :doctor %>
    <%= f.select :doctor_id, @doctors.map{|d| [d.name, d.id]}, {prompt: 'Please select Doctor' }, class: 'form-control', require: true %>
  </div>

  <div class="form-group">
    <%= f.label :appointment_time %>
    <%= f.text_field :appointment_time, class: 'form-control', id: "appointment_time" %>
  </div>

  <div class="form-group">
    <%= f.label :note %>
    <%= f.text_area :note, class: 'form-control' %>
  </div>

  <%= f.button :submit, class: "btn btn-primary" %>
  <%= link_to "Cancel", root_path, class: "btn btn-danger" %>
<% end %>

<script type="text/javascript">
  $('#appointment_time').datetimepicker();
</script>

app/views/appointments/new.html.erb
<%= form_for @appointment, html: { multipart: true, autocomplete: "off" } do |f| %>
	<%= f.hidden_field :patient_id, value: current_user.id %>

  <div class="form-group">
    <%= f.label :doctor %>
    <%= f.select :doctor_id, @doctors.map{|d| [d.name, d.id]}, {prompt: 'Please select Doctor' }, class: 'form-control', require: true %>
  </div>

  <div class="form-group">
    <%= f.label :appointment_time %>
    <%= f.text_field :appointment_time, class: 'form-control', id: "appointment_time", require: true %>
  </div>

  <div class="form-group">
    <%= f.label :note %>
    <%= f.text_area :note, class: 'form-control' %>
  </div>

  <%= f.button :submit, class: "btn btn-primary" %>
  <%= link_to "Cancel", root_path, class: "btn btn-danger" %>
<% end %>

<script type="text/javascript">
  $('#appointment_time').datetimepicker({
  	minDate:0,
  	minTime:'07:00',
  	maxTime:'18:00'
  });
</script>

app/views/home/index.html.erb
<% if @user.role == "doctor" %>
  <div class="col-xs-12 text-center">
    <h1>Hi, <%= current_user.name %></h1>
    <% if @doctor_appointments.present? %>
      <hr/>
      <table class="table">
        <thead>
          <tr>
            <th class="text-left">Patient Name</th>
            <th class="text-left">Appointment Time</th>
            <th class="text-left">Tools</th>
          </tr>
        </thead>
        <tbody>
          <% @doctor_appointments.each do |da| %>
            <tr>
              <td class="text-left"><%= da.patient.name %></td>
              <td class="text-left"><%= da.appointment_time.strftime("%d-%m-%Y %I:%M %P") %></td>
              <td class="text-left">
                <%= link_to "Accept", accept_appointment_path(da), class: "btn btn-primary", style: "margin-right: 5px;" %>
                <%= link_to "Reject", appointment_path(da), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
    <% if @accepted_appointments.present? %>
      <hr/>
      <h4>Accepted Appointments<h4>
      <hr/>
      <table class="table">
        <thead>
          <tr>
            <th class="text-left">Patient Name</th>
            <th class="text-left">Appointment Time</th>
            <th class="text-left">Status</th>
          </tr>
        </thead>
        <tbody>
          <% @accepted_appointments.each do |aa| %>
            <tr>
              <td class="text-left"><%= aa.patient.name %></td>
              <td class="text-left"><%= aa.appointment_time.strftime("%d-%m-%Y %I:%M %P") %></td>
              <td class="text-left">Accepted</td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
<% else %>
  <div class="col-xs-12 text-center">
    <h1>Hi, <%= current_user.name %></h1>
    <% if @doctors.present? %>
      <%= link_to "Book An Appointment", new_appointment_path, class: "btn btn-primary" %>
    <% end %>
    <hr/>
    <% if @booked_appointments.present? %>
      <table class="table">
        <thead>
          <tr>
            <th class="text-left">Doctor Name</th>
            <th class="text-left">Appointment Time</th>
            <th class="text-left">Tools</th>
          </tr>
        </thead>
        <tbody>
          <% @booked_appointments.each do |ba| %>
            <tr>
              <td class="text-left"><%= ba.doctor.name %></td>
              <td class="text-left"><%= ba.appointment_time.strftime("%d-%m-%Y %I:%M %P") %></td>
              <td class="text-left"><%= link_to "edit", edit_appointment_path(ba), class: "btn btn-primary", style: "margin-right: 5px;" %><%= link_to "Delete", appointment_path(ba), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <h4>You don't have booked appointment yet.</h4>
    <% end %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "DoctorManagementSystem", root_path, class: "navbar-brand" %>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li>
          <%= link_to current_user.name, edit_user_path(current_user) %>
        </li>
        <li>
          <%= link_to('<i class="glyphicon glyphicon-off"></i> Logout'.html_safe, destroy_user_session_path, method: :delete) %>
        </li>
      <% else %>
        <li><a href="<%= new_user_registration_path %>"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
        <li><a href="<%= new_user_session_path %>"><span class="glyphicon glyphicon-log-in"></span> Log in</a></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DoctorManagementSystem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% if notice %>
      <div class="alert alert-success" role="alert">
        <%= notice %>
      </div>
    <% elsif alert %>
      <div class="alert alert-danger" role="alert">
        <%= alert %>
      </div>
    <% end %>
    <div class="container">
      <!-- <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p> -->
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/edit.html.erb
<%= form_for @user, html: { multipart: true } do |f| %>
  <% @user.errors.full_messages.each do |msg| %>
      <p><%= msg %></p>
   <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, autofocus: true, required: true, autocomplete: 'name', class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, required: true, autocomplete: 'email', class: 'form-control' %>
  </div>

  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>